language: erlang

sudo: false

otp_release:
  - 20.0
  - 19.3
  - 18.3

notifications:
  email: false

before_script:
  - "curl --silent \"$MANTA_KEY_URL\" --output \"$MANTA_KEY_FILE\""

script: "make test"
